// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: berza_service.proto

package rs.raf.pds.v5.z2.gRPC;

public interface AskResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rs.raf.pds.v5.z2.gRPC.AskResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .rs.raf.pds.v5.z2.gRPC.AskOffer offers = 1;</code>
   */
  java.util.List<rs.raf.pds.v5.z2.gRPC.AskOffer> 
      getOffersList();
  /**
   * <code>repeated .rs.raf.pds.v5.z2.gRPC.AskOffer offers = 1;</code>
   */
  rs.raf.pds.v5.z2.gRPC.AskOffer getOffers(int index);
  /**
   * <code>repeated .rs.raf.pds.v5.z2.gRPC.AskOffer offers = 1;</code>
   */
  int getOffersCount();
  /**
   * <code>repeated .rs.raf.pds.v5.z2.gRPC.AskOffer offers = 1;</code>
   */
  java.util.List<? extends rs.raf.pds.v5.z2.gRPC.AskOfferOrBuilder> 
      getOffersOrBuilderList();
  /**
   * <code>repeated .rs.raf.pds.v5.z2.gRPC.AskOffer offers = 1;</code>
   */
  rs.raf.pds.v5.z2.gRPC.AskOfferOrBuilder getOffersOrBuilder(
      int index);
}
