// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: berza_service.proto

package rs.raf.pds.v5.z2.gRPC;

public interface ClientOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rs.raf.pds.v5.z2.gRPC.Client)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string clientId = 1;</code>
   */
  java.lang.String getClientId();
  /**
   * <code>string clientId = 1;</code>
   */
  com.google.protobuf.ByteString
      getClientIdBytes();

  /**
   * <code>repeated .rs.raf.pds.v5.z2.gRPC.SaleOffer saleOffers = 2;</code>
   */
  java.util.List<rs.raf.pds.v5.z2.gRPC.SaleOffer> 
      getSaleOffersList();
  /**
   * <code>repeated .rs.raf.pds.v5.z2.gRPC.SaleOffer saleOffers = 2;</code>
   */
  rs.raf.pds.v5.z2.gRPC.SaleOffer getSaleOffers(int index);
  /**
   * <code>repeated .rs.raf.pds.v5.z2.gRPC.SaleOffer saleOffers = 2;</code>
   */
  int getSaleOffersCount();
  /**
   * <code>repeated .rs.raf.pds.v5.z2.gRPC.SaleOffer saleOffers = 2;</code>
   */
  java.util.List<? extends rs.raf.pds.v5.z2.gRPC.SaleOfferOrBuilder> 
      getSaleOffersOrBuilderList();
  /**
   * <code>repeated .rs.raf.pds.v5.z2.gRPC.SaleOffer saleOffers = 2;</code>
   */
  rs.raf.pds.v5.z2.gRPC.SaleOfferOrBuilder getSaleOffersOrBuilder(
      int index);

  /**
   * <code>repeated .rs.raf.pds.v5.z2.gRPC.BuyOffer buyOffers = 3;</code>
   */
  java.util.List<rs.raf.pds.v5.z2.gRPC.BuyOffer> 
      getBuyOffersList();
  /**
   * <code>repeated .rs.raf.pds.v5.z2.gRPC.BuyOffer buyOffers = 3;</code>
   */
  rs.raf.pds.v5.z2.gRPC.BuyOffer getBuyOffers(int index);
  /**
   * <code>repeated .rs.raf.pds.v5.z2.gRPC.BuyOffer buyOffers = 3;</code>
   */
  int getBuyOffersCount();
  /**
   * <code>repeated .rs.raf.pds.v5.z2.gRPC.BuyOffer buyOffers = 3;</code>
   */
  java.util.List<? extends rs.raf.pds.v5.z2.gRPC.BuyOfferOrBuilder> 
      getBuyOffersOrBuilderList();
  /**
   * <code>repeated .rs.raf.pds.v5.z2.gRPC.BuyOffer buyOffers = 3;</code>
   */
  rs.raf.pds.v5.z2.gRPC.BuyOfferOrBuilder getBuyOffersOrBuilder(
      int index);

  /**
   * <code>repeated .rs.raf.pds.v5.z2.gRPC.AllShares shares = 4;</code>
   */
  java.util.List<rs.raf.pds.v5.z2.gRPC.AllShares> 
      getSharesList();
  /**
   * <code>repeated .rs.raf.pds.v5.z2.gRPC.AllShares shares = 4;</code>
   */
  rs.raf.pds.v5.z2.gRPC.AllShares getShares(int index);
  /**
   * <code>repeated .rs.raf.pds.v5.z2.gRPC.AllShares shares = 4;</code>
   */
  int getSharesCount();
  /**
   * <code>repeated .rs.raf.pds.v5.z2.gRPC.AllShares shares = 4;</code>
   */
  java.util.List<? extends rs.raf.pds.v5.z2.gRPC.AllSharesOrBuilder> 
      getSharesOrBuilderList();
  /**
   * <code>repeated .rs.raf.pds.v5.z2.gRPC.AllShares shares = 4;</code>
   */
  rs.raf.pds.v5.z2.gRPC.AllSharesOrBuilder getSharesOrBuilder(
      int index);

  /**
   * <code>repeated string symbols = 5;</code>
   */
  java.util.List<java.lang.String>
      getSymbolsList();
  /**
   * <code>repeated string symbols = 5;</code>
   */
  int getSymbolsCount();
  /**
   * <code>repeated string symbols = 5;</code>
   */
  java.lang.String getSymbols(int index);
  /**
   * <code>repeated string symbols = 5;</code>
   */
  com.google.protobuf.ByteString
      getSymbolsBytes(int index);
}
