// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: berza_service.proto

package rs.raf.pds.v5.z2.gRPC;

/**
 * Protobuf type {@code rs.raf.pds.v5.z2.gRPC.CompanyList}
 */
public  final class CompanyList extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:rs.raf.pds.v5.z2.gRPC.CompanyList)
    CompanyListOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CompanyList.newBuilder() to construct.
  private CompanyList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CompanyList() {
    companies_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CompanyList(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              companies_ = new java.util.ArrayList<rs.raf.pds.v5.z2.gRPC.Company>();
              mutable_bitField0_ |= 0x00000001;
            }
            companies_.add(
                input.readMessage(rs.raf.pds.v5.z2.gRPC.Company.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        companies_ = java.util.Collections.unmodifiableList(companies_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return rs.raf.pds.v5.z2.gRPC.BerzaServiceOuterClass.internal_static_rs_raf_pds_v5_z2_gRPC_CompanyList_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return rs.raf.pds.v5.z2.gRPC.BerzaServiceOuterClass.internal_static_rs_raf_pds_v5_z2_gRPC_CompanyList_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            rs.raf.pds.v5.z2.gRPC.CompanyList.class, rs.raf.pds.v5.z2.gRPC.CompanyList.Builder.class);
  }

  public static final int COMPANIES_FIELD_NUMBER = 1;
  private java.util.List<rs.raf.pds.v5.z2.gRPC.Company> companies_;
  /**
   * <code>repeated .rs.raf.pds.v5.z2.gRPC.Company companies = 1;</code>
   */
  public java.util.List<rs.raf.pds.v5.z2.gRPC.Company> getCompaniesList() {
    return companies_;
  }
  /**
   * <code>repeated .rs.raf.pds.v5.z2.gRPC.Company companies = 1;</code>
   */
  public java.util.List<? extends rs.raf.pds.v5.z2.gRPC.CompanyOrBuilder> 
      getCompaniesOrBuilderList() {
    return companies_;
  }
  /**
   * <code>repeated .rs.raf.pds.v5.z2.gRPC.Company companies = 1;</code>
   */
  public int getCompaniesCount() {
    return companies_.size();
  }
  /**
   * <code>repeated .rs.raf.pds.v5.z2.gRPC.Company companies = 1;</code>
   */
  public rs.raf.pds.v5.z2.gRPC.Company getCompanies(int index) {
    return companies_.get(index);
  }
  /**
   * <code>repeated .rs.raf.pds.v5.z2.gRPC.Company companies = 1;</code>
   */
  public rs.raf.pds.v5.z2.gRPC.CompanyOrBuilder getCompaniesOrBuilder(
      int index) {
    return companies_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < companies_.size(); i++) {
      output.writeMessage(1, companies_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < companies_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, companies_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof rs.raf.pds.v5.z2.gRPC.CompanyList)) {
      return super.equals(obj);
    }
    rs.raf.pds.v5.z2.gRPC.CompanyList other = (rs.raf.pds.v5.z2.gRPC.CompanyList) obj;

    boolean result = true;
    result = result && getCompaniesList()
        .equals(other.getCompaniesList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getCompaniesCount() > 0) {
      hash = (37 * hash) + COMPANIES_FIELD_NUMBER;
      hash = (53 * hash) + getCompaniesList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static rs.raf.pds.v5.z2.gRPC.CompanyList parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static rs.raf.pds.v5.z2.gRPC.CompanyList parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static rs.raf.pds.v5.z2.gRPC.CompanyList parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static rs.raf.pds.v5.z2.gRPC.CompanyList parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static rs.raf.pds.v5.z2.gRPC.CompanyList parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static rs.raf.pds.v5.z2.gRPC.CompanyList parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static rs.raf.pds.v5.z2.gRPC.CompanyList parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static rs.raf.pds.v5.z2.gRPC.CompanyList parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static rs.raf.pds.v5.z2.gRPC.CompanyList parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static rs.raf.pds.v5.z2.gRPC.CompanyList parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static rs.raf.pds.v5.z2.gRPC.CompanyList parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static rs.raf.pds.v5.z2.gRPC.CompanyList parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(rs.raf.pds.v5.z2.gRPC.CompanyList prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code rs.raf.pds.v5.z2.gRPC.CompanyList}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:rs.raf.pds.v5.z2.gRPC.CompanyList)
      rs.raf.pds.v5.z2.gRPC.CompanyListOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return rs.raf.pds.v5.z2.gRPC.BerzaServiceOuterClass.internal_static_rs_raf_pds_v5_z2_gRPC_CompanyList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return rs.raf.pds.v5.z2.gRPC.BerzaServiceOuterClass.internal_static_rs_raf_pds_v5_z2_gRPC_CompanyList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              rs.raf.pds.v5.z2.gRPC.CompanyList.class, rs.raf.pds.v5.z2.gRPC.CompanyList.Builder.class);
    }

    // Construct using rs.raf.pds.v5.z2.gRPC.CompanyList.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getCompaniesFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (companiesBuilder_ == null) {
        companies_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        companiesBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return rs.raf.pds.v5.z2.gRPC.BerzaServiceOuterClass.internal_static_rs_raf_pds_v5_z2_gRPC_CompanyList_descriptor;
    }

    @java.lang.Override
    public rs.raf.pds.v5.z2.gRPC.CompanyList getDefaultInstanceForType() {
      return rs.raf.pds.v5.z2.gRPC.CompanyList.getDefaultInstance();
    }

    @java.lang.Override
    public rs.raf.pds.v5.z2.gRPC.CompanyList build() {
      rs.raf.pds.v5.z2.gRPC.CompanyList result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public rs.raf.pds.v5.z2.gRPC.CompanyList buildPartial() {
      rs.raf.pds.v5.z2.gRPC.CompanyList result = new rs.raf.pds.v5.z2.gRPC.CompanyList(this);
      int from_bitField0_ = bitField0_;
      if (companiesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          companies_ = java.util.Collections.unmodifiableList(companies_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.companies_ = companies_;
      } else {
        result.companies_ = companiesBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof rs.raf.pds.v5.z2.gRPC.CompanyList) {
        return mergeFrom((rs.raf.pds.v5.z2.gRPC.CompanyList)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(rs.raf.pds.v5.z2.gRPC.CompanyList other) {
      if (other == rs.raf.pds.v5.z2.gRPC.CompanyList.getDefaultInstance()) return this;
      if (companiesBuilder_ == null) {
        if (!other.companies_.isEmpty()) {
          if (companies_.isEmpty()) {
            companies_ = other.companies_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureCompaniesIsMutable();
            companies_.addAll(other.companies_);
          }
          onChanged();
        }
      } else {
        if (!other.companies_.isEmpty()) {
          if (companiesBuilder_.isEmpty()) {
            companiesBuilder_.dispose();
            companiesBuilder_ = null;
            companies_ = other.companies_;
            bitField0_ = (bitField0_ & ~0x00000001);
            companiesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getCompaniesFieldBuilder() : null;
          } else {
            companiesBuilder_.addAllMessages(other.companies_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      rs.raf.pds.v5.z2.gRPC.CompanyList parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (rs.raf.pds.v5.z2.gRPC.CompanyList) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<rs.raf.pds.v5.z2.gRPC.Company> companies_ =
      java.util.Collections.emptyList();
    private void ensureCompaniesIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        companies_ = new java.util.ArrayList<rs.raf.pds.v5.z2.gRPC.Company>(companies_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        rs.raf.pds.v5.z2.gRPC.Company, rs.raf.pds.v5.z2.gRPC.Company.Builder, rs.raf.pds.v5.z2.gRPC.CompanyOrBuilder> companiesBuilder_;

    /**
     * <code>repeated .rs.raf.pds.v5.z2.gRPC.Company companies = 1;</code>
     */
    public java.util.List<rs.raf.pds.v5.z2.gRPC.Company> getCompaniesList() {
      if (companiesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(companies_);
      } else {
        return companiesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .rs.raf.pds.v5.z2.gRPC.Company companies = 1;</code>
     */
    public int getCompaniesCount() {
      if (companiesBuilder_ == null) {
        return companies_.size();
      } else {
        return companiesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .rs.raf.pds.v5.z2.gRPC.Company companies = 1;</code>
     */
    public rs.raf.pds.v5.z2.gRPC.Company getCompanies(int index) {
      if (companiesBuilder_ == null) {
        return companies_.get(index);
      } else {
        return companiesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .rs.raf.pds.v5.z2.gRPC.Company companies = 1;</code>
     */
    public Builder setCompanies(
        int index, rs.raf.pds.v5.z2.gRPC.Company value) {
      if (companiesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCompaniesIsMutable();
        companies_.set(index, value);
        onChanged();
      } else {
        companiesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .rs.raf.pds.v5.z2.gRPC.Company companies = 1;</code>
     */
    public Builder setCompanies(
        int index, rs.raf.pds.v5.z2.gRPC.Company.Builder builderForValue) {
      if (companiesBuilder_ == null) {
        ensureCompaniesIsMutable();
        companies_.set(index, builderForValue.build());
        onChanged();
      } else {
        companiesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .rs.raf.pds.v5.z2.gRPC.Company companies = 1;</code>
     */
    public Builder addCompanies(rs.raf.pds.v5.z2.gRPC.Company value) {
      if (companiesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCompaniesIsMutable();
        companies_.add(value);
        onChanged();
      } else {
        companiesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .rs.raf.pds.v5.z2.gRPC.Company companies = 1;</code>
     */
    public Builder addCompanies(
        int index, rs.raf.pds.v5.z2.gRPC.Company value) {
      if (companiesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCompaniesIsMutable();
        companies_.add(index, value);
        onChanged();
      } else {
        companiesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .rs.raf.pds.v5.z2.gRPC.Company companies = 1;</code>
     */
    public Builder addCompanies(
        rs.raf.pds.v5.z2.gRPC.Company.Builder builderForValue) {
      if (companiesBuilder_ == null) {
        ensureCompaniesIsMutable();
        companies_.add(builderForValue.build());
        onChanged();
      } else {
        companiesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .rs.raf.pds.v5.z2.gRPC.Company companies = 1;</code>
     */
    public Builder addCompanies(
        int index, rs.raf.pds.v5.z2.gRPC.Company.Builder builderForValue) {
      if (companiesBuilder_ == null) {
        ensureCompaniesIsMutable();
        companies_.add(index, builderForValue.build());
        onChanged();
      } else {
        companiesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .rs.raf.pds.v5.z2.gRPC.Company companies = 1;</code>
     */
    public Builder addAllCompanies(
        java.lang.Iterable<? extends rs.raf.pds.v5.z2.gRPC.Company> values) {
      if (companiesBuilder_ == null) {
        ensureCompaniesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, companies_);
        onChanged();
      } else {
        companiesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .rs.raf.pds.v5.z2.gRPC.Company companies = 1;</code>
     */
    public Builder clearCompanies() {
      if (companiesBuilder_ == null) {
        companies_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        companiesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .rs.raf.pds.v5.z2.gRPC.Company companies = 1;</code>
     */
    public Builder removeCompanies(int index) {
      if (companiesBuilder_ == null) {
        ensureCompaniesIsMutable();
        companies_.remove(index);
        onChanged();
      } else {
        companiesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .rs.raf.pds.v5.z2.gRPC.Company companies = 1;</code>
     */
    public rs.raf.pds.v5.z2.gRPC.Company.Builder getCompaniesBuilder(
        int index) {
      return getCompaniesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .rs.raf.pds.v5.z2.gRPC.Company companies = 1;</code>
     */
    public rs.raf.pds.v5.z2.gRPC.CompanyOrBuilder getCompaniesOrBuilder(
        int index) {
      if (companiesBuilder_ == null) {
        return companies_.get(index);  } else {
        return companiesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .rs.raf.pds.v5.z2.gRPC.Company companies = 1;</code>
     */
    public java.util.List<? extends rs.raf.pds.v5.z2.gRPC.CompanyOrBuilder> 
         getCompaniesOrBuilderList() {
      if (companiesBuilder_ != null) {
        return companiesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(companies_);
      }
    }
    /**
     * <code>repeated .rs.raf.pds.v5.z2.gRPC.Company companies = 1;</code>
     */
    public rs.raf.pds.v5.z2.gRPC.Company.Builder addCompaniesBuilder() {
      return getCompaniesFieldBuilder().addBuilder(
          rs.raf.pds.v5.z2.gRPC.Company.getDefaultInstance());
    }
    /**
     * <code>repeated .rs.raf.pds.v5.z2.gRPC.Company companies = 1;</code>
     */
    public rs.raf.pds.v5.z2.gRPC.Company.Builder addCompaniesBuilder(
        int index) {
      return getCompaniesFieldBuilder().addBuilder(
          index, rs.raf.pds.v5.z2.gRPC.Company.getDefaultInstance());
    }
    /**
     * <code>repeated .rs.raf.pds.v5.z2.gRPC.Company companies = 1;</code>
     */
    public java.util.List<rs.raf.pds.v5.z2.gRPC.Company.Builder> 
         getCompaniesBuilderList() {
      return getCompaniesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        rs.raf.pds.v5.z2.gRPC.Company, rs.raf.pds.v5.z2.gRPC.Company.Builder, rs.raf.pds.v5.z2.gRPC.CompanyOrBuilder> 
        getCompaniesFieldBuilder() {
      if (companiesBuilder_ == null) {
        companiesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            rs.raf.pds.v5.z2.gRPC.Company, rs.raf.pds.v5.z2.gRPC.Company.Builder, rs.raf.pds.v5.z2.gRPC.CompanyOrBuilder>(
                companies_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        companies_ = null;
      }
      return companiesBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:rs.raf.pds.v5.z2.gRPC.CompanyList)
  }

  // @@protoc_insertion_point(class_scope:rs.raf.pds.v5.z2.gRPC.CompanyList)
  private static final rs.raf.pds.v5.z2.gRPC.CompanyList DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new rs.raf.pds.v5.z2.gRPC.CompanyList();
  }

  public static rs.raf.pds.v5.z2.gRPC.CompanyList getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CompanyList>
      PARSER = new com.google.protobuf.AbstractParser<CompanyList>() {
    @java.lang.Override
    public CompanyList parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CompanyList(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CompanyList> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CompanyList> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public rs.raf.pds.v5.z2.gRPC.CompanyList getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

