// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: berza_service.proto

package rs.raf.pds.v5.z2.gRPC;

public interface CompanyListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rs.raf.pds.v5.z2.gRPC.CompanyList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .rs.raf.pds.v5.z2.gRPC.Company companies = 1;</code>
   */
  java.util.List<rs.raf.pds.v5.z2.gRPC.Company> 
      getCompaniesList();
  /**
   * <code>repeated .rs.raf.pds.v5.z2.gRPC.Company companies = 1;</code>
   */
  rs.raf.pds.v5.z2.gRPC.Company getCompanies(int index);
  /**
   * <code>repeated .rs.raf.pds.v5.z2.gRPC.Company companies = 1;</code>
   */
  int getCompaniesCount();
  /**
   * <code>repeated .rs.raf.pds.v5.z2.gRPC.Company companies = 1;</code>
   */
  java.util.List<? extends rs.raf.pds.v5.z2.gRPC.CompanyOrBuilder> 
      getCompaniesOrBuilderList();
  /**
   * <code>repeated .rs.raf.pds.v5.z2.gRPC.Company companies = 1;</code>
   */
  rs.raf.pds.v5.z2.gRPC.CompanyOrBuilder getCompaniesOrBuilder(
      int index);
}
