// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: berza_service.proto

package rs.raf.pds.v5.z2.gRPC;

public interface TransactionsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rs.raf.pds.v5.z2.gRPC.TransactionsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .rs.raf.pds.v5.z2.gRPC.Transaction transactions = 1;</code>
   */
  java.util.List<rs.raf.pds.v5.z2.gRPC.Transaction> 
      getTransactionsList();
  /**
   * <code>repeated .rs.raf.pds.v5.z2.gRPC.Transaction transactions = 1;</code>
   */
  rs.raf.pds.v5.z2.gRPC.Transaction getTransactions(int index);
  /**
   * <code>repeated .rs.raf.pds.v5.z2.gRPC.Transaction transactions = 1;</code>
   */
  int getTransactionsCount();
  /**
   * <code>repeated .rs.raf.pds.v5.z2.gRPC.Transaction transactions = 1;</code>
   */
  java.util.List<? extends rs.raf.pds.v5.z2.gRPC.TransactionOrBuilder> 
      getTransactionsOrBuilderList();
  /**
   * <code>repeated .rs.raf.pds.v5.z2.gRPC.Transaction transactions = 1;</code>
   */
  rs.raf.pds.v5.z2.gRPC.TransactionOrBuilder getTransactionsOrBuilder(
      int index);
}
