// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: berza_service.proto

package rs.raf.pds.v5.z2.gRPC;

public interface TransactionsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rs.raf.pds.v5.z2.gRPC.TransactionsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string timestamp = 1;</code>
   */
  java.lang.String getTimestamp();
  /**
   * <code>string timestamp = 1;</code>
   */
  com.google.protobuf.ByteString
      getTimestampBytes();

  /**
   * <code>string symbol = 2;</code>
   */
  java.lang.String getSymbol();
  /**
   * <code>string symbol = 2;</code>
   */
  com.google.protobuf.ByteString
      getSymbolBytes();
}
