// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: berza_service.proto

package rs.raf.pds.v5.z2.gRPC;

public interface TransactionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rs.raf.pds.v5.z2.gRPC.Transaction)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string buyerClientId = 1;</code>
   */
  java.lang.String getBuyerClientId();
  /**
   * <code>string buyerClientId = 1;</code>
   */
  com.google.protobuf.ByteString
      getBuyerClientIdBytes();

  /**
   * <code>string sellerClientId = 2;</code>
   */
  java.lang.String getSellerClientId();
  /**
   * <code>string sellerClientId = 2;</code>
   */
  com.google.protobuf.ByteString
      getSellerClientIdBytes();

  /**
   * <code>string symbol = 3;</code>
   */
  java.lang.String getSymbol();
  /**
   * <code>string symbol = 3;</code>
   */
  com.google.protobuf.ByteString
      getSymbolBytes();

  /**
   * <code>int32 numberOfShares = 4;</code>
   */
  int getNumberOfShares();

  /**
   * <code>double price = 5;</code>
   */
  double getPrice();

  /**
   * <code>.google.protobuf.Timestamp timestamp = 6;</code>
   */
  boolean hasTimestamp();
  /**
   * <code>.google.protobuf.Timestamp timestamp = 6;</code>
   */
  com.google.protobuf.Timestamp getTimestamp();
  /**
   * <code>.google.protobuf.Timestamp timestamp = 6;</code>
   */
  com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder();
}
